version: '3.8'

services:
  mapserver:
    image: camptocamp/mapserver:7.6
    ports:
      - "8080:80"
    volumes:
      - ./mapserver:/etc/mapserver
      - ./data:/data
    environment:
      - MS_MAPFILE=/etc/mapserver/harita.map
      - MS_CORS_ENABLED=true
    restart: always

  web_arayuz:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/data # <-- NGINX'İN TERRAIN KLASÖRÜNÜ OKUYABİLMESİ İÇİN BU SATIRI EKLEDİK
    restart: always