version: '3.8'

services:
  mapserver:
    image: camptocamp/mapserver:7.6
    ports:
      - "8080:80"
    volumes:
      # Bilgisayarındaki tek bir 'volumes' klasörünü konteynerin içine köprüledik
      - ./volumes:/etc/mapserver/volumes
    environment:
      # Haritanın konteyner içindeki tam ve kesin yeri artık burası:
      - MS_MAPFILE=/etc/mapserver/volumes/mapfiles/harita.map
      - MS_CORS_ENABLED=true
    restart: always

  web_arayuz:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Nginx'in .terrain dosyalarını okuyabilmesi için ortak volumes/data klasörünü bağladık:
      - ./volumes/data:/data
    restart: always