events {
    worker_connections 1024;
}

http {
    # Nginx'in tüm standart MIME tiplerini (js, css, html vb.) yüklemesini sağlar
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Cesium Web Worker'ları için tarayıcıya doğru MIME tipini zorla dikte ediyoruz
    types {
        application/javascript js mjs;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html; # React Router rotaları için koruma
        }
    }
}