events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    types {
        application/javascript js mjs;
    }

    server {
        listen 80;
        server_name localhost;

        # React Ön Yüzü
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # --- EN KARARLI TERRAIN AYARI ---
        # Karmaşık yönlendirmeler yerine doğrudan dosyaların uzantısına göre kuralları ayırıyoruz
        
        # Eğer talep edilen dosya layer.json ise
        location ~* terrain/.*\.json$ {
            root /data;
            add_header Access-Control-Allow-Origin *;
            default_type application/json;
        }

        # Eğer talep edilen dosya .terrain tile parçası ise (Gzip sıkıştırmasını aç)
        location ~* terrain/.*\.terrain$ {
            root /data;
            add_header Access-Control-Allow-Origin *;
            add_header Content-Encoding gzip;
            default_type application/octet-stream;
        }
    }
}